{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# **Traffic Sign Recognition** \n",
    "\n",
    "## Writeup\n",
    "\n",
    "\n",
    "\n",
    "---\n",
    "\n",
    "**Build a Traffic Sign Recognition Project**\n",
    "\n",
    "The goals / steps of this project are the following:\n",
    "* Load the data set (see below for links to the project data set)\n",
    "* Explore, summarize and visualize the data set\n",
    "* Design, train and test a model architecture\n",
    "* Use the model to make predictions on new images\n",
    "* Analyze the softmax probabilities of the new images\n",
    "* Summarize the results with a written report\n",
    "\n",
    "\n",
    "[//]: # (Image References)\n",
    "\n",
    "[stopSign]: ./newTest/stop_.png \"Stop sign\"\n",
    "[30kmphSign]: ./newTest/30_.png \"30kmph sign\"\n",
    "[yeildSign]: ./newTest/yield_.png \"Yeild sign\"\n",
    "[noentrySign]: ./newTest/noentry_.png \"Noentry sign\"\n",
    "[rightSign]: ./newTest/right_.png \"Right sign\"\n",
    "\n",
    "[reportImage1]: ./report/reportImage1.png \"Data Vis\"\n",
    "[softMax]: ./report/softmax.png \"Softmax Vis\"\n",
    "\n",
    "\n",
    "## Rubric Points\n",
    "### Here I will consider the [rubric points](https://review.udacity.com/#!/rubrics/481/view) individually and describe how I addressed each point in my implementation.  \n",
    "\n",
    "---\n",
    "### Writeup / README\n",
    "\n",
    "#### 1. Provide a Writeup / README that includes all the rubric points and how you addressed each one. You can submit your writeup as markdown or pdf. You can use this template as a guide for writing the report. The submission includes the project code.\n",
    "\n",
    "This file contains the writeup. In addition subbmited with this \n",
    "\n",
    "### Data Set Summary & Exploration\n",
    "\n",
    "#### 1. Provide a basic summary of the data set. In the code, the analysis should be done using python, numpy and/or pandas methods rather than hardcoding results manually.\n",
    "\n",
    "I used the pandas library to calculate summary statistics of the traffic\n",
    "signs data set:\n",
    "\n",
    "* The size of training set is 34,799\n",
    "* The size of the validation set is 4,410\n",
    "* The size of test set is 12,630\n",
    "* The shape of a traffic sign image is (32,32,3)\n",
    "* The number of unique classes/labels in the data set is 43\n",
    "\n",
    "#### 2. Include an exploratory visualization of the dataset.\n",
    "\n",
    "Here is an exploratory visualization of the data set. It is a sample for each of the 43 types of traffic sign present in the dataset.\n",
    "\n",
    "![alt text][reportImage1]\n",
    "\n",
    "### Design and Test a Model Architecture\n",
    "\n",
    "#### 1. Describe how you preprocessed the image data. What techniques were chosen and why did you choose these techniques? Consider including images showing the output of each preprocessing technique. Pre-processing refers to techniques such as converting to grayscale, normalization, etc. (OPTIONAL: As described in the \"Stand Out Suggestions\" part of the rubric, if you generated additional data for training, describe why you decided to generate additional data, how you generated the data, and provide example images of the additional data. Then describe the characteristics of the augmented training set like number of images in the set, number of images for each class, etc.)\n",
    "\n",
    "I decided to keep the colour channels for all the images. There was conflicting information for benefits of greyscale and colour images.\n",
    "\n",
    "I normalised the images in the hope that it would provide better numerical stability.\n",
    "\n",
    "I didn't create additional data. Instead I took care of overfitting in the model architechture by including dropout.\n",
    "\n",
    "\n",
    "#### 2. Describe what your final model architecture looks like including model type, layers, layer sizes, connectivity, etc.) Consider including a diagram and/or table describing the final model.\n",
    "\n",
    "My final model consisted of the following layers:\n",
    "\n",
    "| Layer         \t\t|     Description\t        \t\t\t\t\t| \n",
    "|:---------------------:|:---------------------------------------------:| \n",
    "| Input         \t\t| 32x32x3 RGB image   \t\t\t\t\t\t\t| \n",
    "| Convolution 3x3     \t| 1x1 stride, valid padding, outputs 28x28x12 \t|\n",
    "| RELU\t\t\t\t\t|\t\t\t\t\t\t\t\t\t\t\t\t|\n",
    "| Max pooling\t      \t| 2x2 stride,  outputs 14x14x12 \t\t\t\t|\n",
    "| Convolution 3x3\t    | 1x1 stride, valid padding, outputs 10x10x32   |\n",
    "| RELU\t\t\t\t\t|\t\t\t\t\t\t\t\t\t\t\t\t|\n",
    "| Max pooling\t      \t| 2x2 stride,  outputs 5x5x32 \t\t\t\t    |\n",
    "| Dropout\t      \t    | Variable keep_prob (0.5,0.75.0.8)\t\t\t\t|\n",
    "| Flatten        \t\t| Output 800       \t\t\t\t\t\t\t\t|\n",
    "| Fully connected\t    | Output 120    \t\t\t\t\t\t\t\t|\n",
    "| RELU\t\t\t\t\t|\t\t\t\t\t\t\t\t\t\t\t\t|\n",
    "| Dropout\t      \t    | Variable keep_prob (0.5,0.75.0.8)\t\t\t\t|\n",
    "| Fully connected\t    | Output 84     \t\t\t\t\t\t\t\t| \n",
    "| RELU\t\t\t\t\t|\t\t\t\t\t\t\t\t\t\t\t\t|\n",
    "| Fully connected\t    | Output 43     \t\t\t\t\t\t\t\t| \n",
    "\n",
    "#### 3. Describe how you trained your model. The discussion can include the type of optimizer, the batch size, number of epochs and any hyperparameters such as learning rate.\n",
    "\n",
    "To train the model I used a batch size of 128, 50 epochs and an initial learning rate of 0.001. \n",
    "\n",
    "After 29 epochs the learning rate was decreased to 0.0001 and again reducded to 0.00001 for the final epoch.\n",
    "\n",
    "The dropout rate started at 50% but after 29 epocs was decreased to 25% and finally to 20% for the final epoch.\n",
    "\n",
    "#### 4. Describe the approach taken for finding a solution and getting the validation set accuracy to be at least 0.93. Include in the discussion the results on the training, validation and test sets and where in the code these were calculated. Your approach may have been an iterative process, in which case, outline the steps you took to get to the final solution and why you chose those steps. Perhaps your solution involved an already well known implementation or architecture. In this case, discuss why you think the architecture is suitable for the current problem.\n",
    "\n",
    "My final model results were:\n",
    "* training set accuracy of 100%\n",
    "* validation set accuracy of 98%\n",
    "* test set accuracy of 96.7%\n",
    "\n",
    "If an iterative approach was chosen:\n",
    "* The first architecture I used was a LeNet. Class readings had suggested that this would perform fairly well.\n",
    "* There were some problems with the initial model overfitting. Common solutions to this problem are to generate additional images or change the architecture.\n",
    "* I decided to include dropout layers and at the same time increase the number of filters in the hope that the model would be forced to learn many ways of identifying a sign.\n",
    "* The dropout rate had to be experiemented with. Given I increased the number of filters substantially I decided it turned out a 50% dropout rate was quite good. I then had this decrease as the model trained in order to reinforce the learned pathways.\n",
    "* Ultimatly, the dropout was quite succesfull at reducing overfitting.\n",
    "\n",
    " \n",
    "\n",
    "### Test a Model on New Images\n",
    "\n",
    "#### 1. Choose five German traffic signs found on the web and provide them in the report. For each image, discuss what quality or qualities might be difficult to classify.\n",
    "\n",
    "Here are five German traffic signs that I found on the web:\n",
    "![alt text][stopSign] ![alt text][30kmphSign] ![alt text][yeildSign]\n",
    "![alt text][noentrySign] ![alt text][rightSign]\n",
    "\n",
    "I expected the stop sign to be easily predicted given the unique shape of the sign and for this particular image, the contrast beween the blue sky and the red sign.\n",
    "\n",
    "For the 30km/hr and yeild signs I expected it to be easily predicted given the image is taken almost straight on facing the sign. I assumed the green background might cause some problems.\n",
    "\n",
    "The no entry sign was taken on a skew. Hence I expected this to struggle with prediction more than the other signs.\n",
    "\n",
    "Finally, the right turn sign is blue and on a clear skyblue background. As such I expected this one to struggle in prediciton given that even for human eyes it may be tricky.\n",
    "\n",
    "\n",
    "#### 2. Discuss the model's predictions on these new traffic signs and compare the results to predicting on the test set. At a minimum, discuss what the predictions were, the accuracy on these new predictions, and compare the accuracy to the accuracy on the test set (OPTIONAL: Discuss the results in more detail as described in the \"Stand Out Suggestions\" part of the rubric).\n",
    "\n",
    "Here are the results of the prediction:\n",
    "\n",
    "| Image\t\t\t        |     Prediction\t        \t\t\t\t\t| \n",
    "|:---------------------:|:---------------------------------------------:| \n",
    "| Stop Sign      \t\t| Yeild                                         |\n",
    "| 30km/hr     \t\t\t| 30km/hr  \t\t\t\t\t\t\t\t\t\t|\n",
    "| Right turn\t\t\t| Right turn\t\t\t\t\t\t\t\t\t|\n",
    "| Yeild  \t      \t\t| Yeild     \t\t\t\t\t \t\t\t\t|\n",
    "| No entry  \t\t\t| Priority road      \t\t\t\t\t\t\t|\n",
    "\n",
    "\n",
    "The model was able to correctly guess 3 of the 5 traffic signs, which gives an accuracy of 60%. This is quite a bit lower than the results for the test dataset though not unexpected given the small sample size of 5 signs.\n",
    "\n",
    "#### 3. Describe how certain the model is when predicting on each of the five new images by looking at the softmax probabilities for each prediction. Provide the top 5 softmax probabilities for each image along with the sign type of each probability. (OPTIONAL: as described in the \"Stand Out Suggestions\" part of the rubric, visualizations can also be provided such as bar charts)\n",
    "\n",
    "The code for making predictions on my final model is located in the 11th cell of the Ipython notebook.\n",
    "\n",
    "The distribution of probabilities for the 5 signs can be seen in the image below.\n",
    "\n",
    "We can see that the stop sign (Top Left 14) guessed stop sign as the number three probability substantially below the first and second. The 2nd through 4th images were all predicted correctly. Finally the last image,no entry, was incorrectly predicted and didnt even have the correct sign in the top 5 spots.\n",
    "\n",
    "![alt text][softmax]\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  },
  "widgets": {
   "state": {},
   "version": "1.1.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
